### ISSUE TITLE
nvEnc.EncodeSingleFrame has a high CPU usage

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#100]
**Describe the bug**
Hi, @rarzumanyan. I run the [SampleEncode.py](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleEncode.py) and find that the CPU usage is high (nearly 100% on one of my machine, highest ~8000% on my another advanced machine) when the script is running. I read the blog on  [NVIDIA Developer websites](https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/), I notice that "DecodeSingleFrame" operation does Device to Host memory copy. Similar to this, the "EncodeSingleFrame" method may does the same thing.  According to my understanding, "Device to Host memory copy" may not use so many CPU operations but need large I/O. The high CPU usage of "nvEnc.EncodeSingleFrame" slow down the other process in my application. Can you provide some help such as limit the CPU usage of VPF?

**To Reproduce**
1.  Run SampleEncode.py using the a raw NV12 file to generate a h264 file.
2. Use top/htop command and watch the high CPU usage of the encode process.

**Expected behavior**
Reduce the CPU usage when nvEnc.EncodeSingleFrame is running.

**Screenshots**
On Desktop1, when I run the script, the CPU usage nearly 100%.
![image](https://user-images.githubusercontent.com/22371026/91382798-1929e500-e85d-11ea-9c87-cd5ee9989207.png)
![image](https://user-images.githubusercontent.com/22371026/91382845-3d85c180-e85d-11ea-8e49-1b7e030d655a.png)

On Desktop2, when I run the script, the highest CPU usage nearly 8000%.
![image](https://user-images.githubusercontent.com/22371026/91382913-6908ac00-e85d-11ea-9dd8-c8a6e1dd980c.png)

**Desktop1:**
 - OS: ubuntu 18.04
 - Nvidia driver version: 440.82
 - CUDA Version: 10.1
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.6.10

**Desktop2:**
 - OS: ubuntu 18.04
 - Nvidia driver version: 440.64.00
 - CUDA Version: 10.2
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.7.7
 - CPU(s):  96
 - On-line CPU(s) list: 0-95

**Additional context**
Is there any advice to reduce the CPU usage when the "nvEnc.EncodeSingleFrame" method runs?

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

First I recommend to isolate the issue and make sure that the very `EncodeSingleFrame` method is slowing everything down.
This method accepts large raw frames (3Mb per FullHD YUV frame) which are taken from HDD or SSD usually so this may impact performance as well. You can comment out the call and check the CPU usage without actual encoding.

P. S.
The `EncodeSingleFrame` method itself is absolutely minimal piece of code - it only does HtoD memcpy and kicks of encoding so there's nothing to get rid of really.

**Comment by TracelessLe** [comment]
> Hi @TracelessLe
> 
> First I recommend to isolate the issue and make sure that the very `EncodeSingleFrame` method is slowing everything down.
> This method accepts large raw frames (3Mb per FullHD YUV frame) which are taken from HDD or SSD usually so this may impact performance as well. You can comment out the call and check the CPU usage without actual encoding.
> 
> P. S.
> The `EncodeSingleFrame` method itself is absolutely minimal piece of code - it only does HtoD memcpy and kicks of encoding so there's nothing to get rid of really.

Thanks a lot. Follow your advice, I take some tests to find out the culprit of high CPU usage. Input video from HDD/SSD spend ~35% CPU and it is acceptable. From more experiments, even I read video data from memory directly, the process spend large CPU still. After a closer look in my code, I find that I add  "cv2.cvtColor(rawFrame, cv2.COLOR_BGR2YUV_I420)" to transform the BGR data to YUV format in my application, it does spend large CPU!

At the present stage, I first use opencv to transform BGR to YUV, then "UploadSingleFrame" and finally use nvc.PySurfaceConverter to convert YUV to NV12. Is there any method to convert OpenCV mat/umat to PyNvCodec.Surface, or does the PyNvCodec.PySurfaceConverter() method surpport to convert RGB/BGR pixel format to NV12?  I would be grateful if I could get some help.

Thanks again.

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

>At the present stage, I first use opencv to transform BGR to YUV, then "UploadSingleFrame" and finally use nvc.PySurfaceConverter to convert YUV to NV12. Is there any method to convert OpenCV mat/umat to PyNvCodec.Surface, or does the PyNvCodec.PySurfaceConverter() method surpport to convert RGB/BGR pixel format to NV12? I would be grateful if I could get some help.

VPF supports RGB->YUV420 and YUV420->NV12 with Nvidia NPP library.
It's very easy to add BGR->YUV420 support, but NPP doesn't support BGR->NV12 conversion so far.
So it would still require 2 steps to proceed.

**Comment by TracelessLe** [comment]
> Hi @TracelessLe
> 
> > At the present stage, I first use opencv to transform BGR to YUV, then "UploadSingleFrame" and finally use nvc.PySurfaceConverter to convert YUV to NV12. Is there any method to convert OpenCV mat/umat to PyNvCodec.Surface, or does the PyNvCodec.PySurfaceConverter() method surpport to convert RGB/BGR pixel format to NV12? I would be grateful if I could get some help.
> 
> VPF supports RGB->YUV420 and YUV420->NV12 with Nvidia NPP library.
> It's very easy to add BGR->YUV420 support, but NPP doesn't support BGR->NV12 conversion so far.
> So it would still require 2 steps to proceed.

Hi @rarzumanyan , I get a problem when I try to use VPF to do convert incluce RGB->YUV420 and YUV420->NV12. 

If I use "rawFrameRGB = cv2.cvtColor(rawFrameBGR, cv2.COLOR_BGR2RGB)" to transform BGR (read a video/image using OpenCV) to RGB, the output video is normal put it through VPF 2 steps convertion. 
![image](https://user-images.githubusercontent.com/22371026/91531410-58c8fd80-e93f-11ea-9388-12e98bcaaebb.png)

But when I use "rawFrameRGB = rawFrameBGR[:,:,::-1]" to do the BGR2RGB, I get a wrong result through VPF 2 steps convertion. 
![image](https://user-images.githubusercontent.com/22371026/91531453-65e5ec80-e93f-11ea-9c6c-7f9069cb5f5f.png)

As you can see, the color is different.

After analysis, I find that the data is not equal when the two kinds frameRGB I generate has been "UploadSingleFrame" and "DownloadSingleSurface" respectively.
The code I use:
` 
nvUpl_rgb = nvc.PyFrameUploader(int(width), int(height), nvc.PixelFormat.RGB, gpuID)
nvCvt_rgb2yuv = nvc.PySurfaceConverter(int(width), int(height), nvc.PixelFormat.RGB, nvc.PixelFormat.YUV420, gpuID)
nvCvt_yuv2nv12 = nvc.PySurfaceConverter(int(width), int(height), nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
nvDwn = nvc.PySurfaceDownloader(width, height, nvc.PixelFormat.RGB, gpuID)

rawFrameRGB = cv2.cvtColor(rawFrameBGR, cv2.COLOR_BGR2RGB)#use opencv to do BGR2RGB
#rawFrameRGB = rawFrame[:,:,::-1]#use numpy reverse method to do BGR2RGB

rawSurface = nvUpl_rgb.UploadSingleFrame(rawFrameRGB)
if (rawSurface.Empty()):
    print('Failed to upload video frame to GPU')
    break

rawFrame = np.ndarray(shape=(width, height, 3), dtype=np.uint8)
success = nvDwn.DownloadSingleSurface(rawSurface, rawFrame)
if(success):
    print(rawFrame)
`
The orignal BGR data is:
```
[[[ 78  64  62]
  [ 78  64  62]
  [ 78  64  62]
  ...
  [ 95  81  74]
  [ 95  81  74]
  [ 95  81  74]]
 ...
  [138 130 132]
  [138 130 132]
  [138 130 132]]

 [[150 141 145]
  [150 141 145]
  [150 141 145]
  ...
  [150 142 144]
  [150 142 144]
  [150 142 144]]]
```

The data after opencv or numpy transform is:
```
[[[ 62  64  78]
  [ 62  64  78]
  [ 62  64  78]
  ...
  [ 74  81  95]
  [ 74  81  95]
  [ 74  81  95]]
  ...
  [132 130 138]
  [132 130 138]
  [132 130 138]]

 [[145 141 150]
  [145 141 150]
  [145 141 150]
  ...
  [144 142 150]
  [144 142 150]
  [144 142 150]]]
```

The output after "UploadSingleFrame" and "DownloadSingleSurface"  using opencv BGR2RGB as input is equal to the input totally.

But the output using numpy reverse method is strange:
`
[[[ 62  **78  64**]
  [ 62  78  64]
  [ 62  78  64]
  ...
  [ 74  95  81]
  [ 74  95  81]
  [ 74  95  81]]
  ...
  [132 138 130]
  [132 138 130]
  [132 138 130]]

 [[132 138 130]
  [132 138 130]
  [132 138 130]
  ...
  [144 150 142]
  [144 150 142]
  [144  **78  65**]]]
`
I find the order of 2 and 3 channel is reversed, and the last 2 numbers is so wreid...

The code and test video I use is attached:

[code_and_testVideo.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5140751/code_and_testVideo.zip)

The "SampleDecodeEncode.py" is code, "test.mp4" is original video, "test-gpu-opencv.mp4" is output video when I use opencv BGR2RGB, "test-gpu-numpy.mp4" is output video using numpy reverse method to do 'BGR2RGB'.

Can you provide some advice? Thanks a lot!

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

I'm not a Python developer, so I can't give you any useful advice here.
For me it would be much easier to add BGR->YUV conversion on CUDA cores with NPP :)

**Comment by TracelessLe** [comment]
> Hi @TracelessLe
> 
> I'm not a Python developer, so I can't give you any useful advice here.
> For me it would be much easier to add BGR->YUV conversion on CUDA cores with NPP :)

Fine, thank you all the same!  :)

**Comment by rarzumanyan** [comment]
@TracelessLe 

I've added GPU-accelerated NV12->BGR and BGR->YUV420 color conversion.
Check out latest commit in master branch.

**Comment by TracelessLe** [comment]
> @TracelessLe
> 
> I've added GPU-accelerated NV12->BGR and BGR->YUV420 color conversion.
> Check out latest commit in master branch.

I am grateful for your support :)

**Comment by sniklaus** [comment]
Is it me or is the new BGR->YUV420 conversion wrong (YUV != YCbCr)?

https://github.com/NVIDIA/VideoProcessingFramework/blob/77f1c25b813d2bb6488444daf999e76118d1e36e/PyNvCodec/TC/src/TasksColorCvt.cpp#L222

**Comment by sniklaus** [comment]
Something seems wrong with the new BGR->YUV420 path. I replaced my existing code, which first converted the frames from BGR to RGB before feeding them to UploadSingleFrame and then went from RGB to YUV420 to NV12, to feeding the BGR frames to UploadSingleFrame and then going from BGR to YUV420 to NV12. However, the resulting video looks desaturated and is subject to about a 10 dB drop in quality. Any suggestions?

**Comment by rarzumanyan** [comment]
Hi @sniklaus 

You're about BGR->YUV conversion, it's actually BGR->YCbCr (which isn't YUV).
Need to rename that to avoid confusion.

**Comment by rarzumanyan** [comment]
@sniklaus 
I've pushed patch to master branch that adds YCbCr pixel format so that now it's proper BGR->YCbCr conversion.

**Comment by sniklaus** [comment]
I was initially thinking that too. However, there is more to it then that since the following works but shouldn't.

1. `rgb_yuv420` which uses `nppiRGBToYUV420_8u_C3P3R_Ctx`
2. `yuv420_nv12` which uses `nppiYCbCr420_8u_P3P2R_Ctx`
3. encode frames
4. decode frames
5. `nv12_rgb` which uses `nppiNV12ToRGB_709HDTV_8u_P2C3R_Ctx`

Notice that `yuv420_nv12` is actually using YCbCr and not YUV as input. Still, this pipeline works just fine and I can get a PSNR between the input frames and the encoded/decoded frames of 40+ with a sufficiently high bitrate. Furthermore, if I change `nppiRGBToYUV420_8u_C3P3R_Ctx` to `nppiRGBToYCbCr420_8u_C3P3R_Ctx` in `rgb_yuv420` then the PSNR drops to 30 with the same bitrate even though this should work because `yuv420_nv12` is allegedly using YCbCr. What am I missing?

**Comment by rarzumanyan** [comment]
@sniklaus 

`nppiYCbCr420_8u_P3P2R_Ctx` only resamples the chroma plane, it doesn't change the pixel values:
https://docs.nvidia.com/cuda/npp/group__image__color__sampling__format__conversion.html#ga39c6fb9e30ce97adf75281190f74bfe5

**Comment by sniklaus** [comment]
I see, thanks for the explanation! So what is the `bgr_ycbcr` good for then if there is nothing else that uses YCbCr? Please correct me if I am wrong, but it seems like I still cannot use the provided pipeline to go from BGR to NV12.
